DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS cloud;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT  NOT NULL
);

CREATE TABLE cloud (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cloudname TEXT NOT NULL,
    description TEXT NOT NULL,
    image BLOB NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);